spring.application.name=spring_kadai_todo
Step4. 接続設定（application.properties）
spring.datasource.url=jdbc:mysql://localhost:3306/spring_db_kadai?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=（自分のパスワード）
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect